### ISSUE TITLE
Missing 'npy' files

### ISSUE THREAD

**Issue by DevikalyanDas** [silviazuffi/awol#1]
Hello @silviazuffi, 

Thanks for your nice work and congrats. I think the npy files for animals clip test set interpolate i.e., "out_testset_animal_realnvp_mask_animal_clip_features_testset_interpolation.npy" is missing. Can you please provide this also?

Thanks,
Devikalyan Das

**Comment by silviazuffi** [comment]
Hi,
Thanks. The file you mentioned is an output file, I have however added it.

Best
